apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  namespace: default
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: 535002861869.dkr.ecr.us-east-1.amazonaws.com/dvps:20250701183848
#        ports:
#        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: default
spec:
  type:  LoadBalancer
  selector:
    app: python
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000 # porta da aplicação
      name: app
    - protocol: TCP
      port: 7000
      targetPort: 7000 # porta para a coleta de métricas
      name: metrics




